# Generated by Django 6.0.1 on 2026-01-26 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(default='Cameroonian', max_length=50),
        ),
    ]
