# Generated by Django 6.0.1 on 2026-01-20 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_alter_grade_options_alter_grade_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='evaluated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
