# Generated by Django 6.0.1 on 2026-01-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0004_alter_grade_options_alter_exam_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_time',
            field=models.TimeField(null=True, verbose_name=''),
        ),
    ]
