# Generated by Django 6.0.1 on 2026-01-25 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0005_exam_exam_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_time',
            field=models.TimeField(null=True, verbose_name='Time'),
        ),
    ]
