# Generated by Django 6.0.1 on 2026-01-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='st8.jpg', null=True, upload_to='profiles/'),
        ),
    ]
