# Generated by Django 6.0.1 on 2026-01-26 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='Model Public School', max_length=200)),
                ('school_address', models.TextField(blank=True, default='123 Education Street, Knowledge City')),
                ('school_phone', models.CharField(blank=True, default='+1 234 567 8900', max_length=20)),
                ('school_email', models.EmailField(blank=True, default='info@school.com', max_length=254)),
                ('school_logo', models.ImageField(blank=True, null=True, upload_to='school_branding/')),
                ('current_session', models.CharField(default='2023-2024', help_text='e.g. 2023-2024', max_length=20)),
                ('current_term', models.CharField(choices=[('1', 'First Term'), ('2', 'Second Term'), ('3', 'Third Term')], default='1', max_length=20)),
            ],
            options={
                'verbose_name': 'School Settings',
                'verbose_name_plural': 'School Settings',
            },
        ),
    ]
