# Generated by Django 6.0.1 on 2026-01-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_accessrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='approval_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='approval_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='rejection_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='rejection_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
