# Generated by Django 6.0.1 on 2026-01-09 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('qualification', models.CharField(choices=[('B.Ed', 'Bachelor of Education'), ('M.Ed', 'Master of Education'), ('B.Sc', 'Bachelor of Science'), ('M.Sc', 'Master of Science'), ('B.A', 'Bachelor of Arts'), ('M.A', 'Master of Arts'), ('Ph.D', 'Doctor of Philosophy'), ('Other', 'Other')], max_length=50)),
                ('specialization', models.CharField(max_length=100)),
                ('designation', models.CharField(choices=[('Principal', 'Principal'), ('Vice Principal', 'Vice Principal'), ('Head Teacher', 'Head Teacher'), ('Senior Teacher', 'Senior Teacher'), ('Teacher', 'Teacher'), ('Assistant Teacher', 'Assistant Teacher'), ('Trainee Teacher', 'Trainee Teacher')], default='Teacher', max_length=50)),
                ('joining_date', models.DateField()),
                ('experience_years', models.IntegerField(default=0)),
                ('previous_school', models.CharField(blank=True, max_length=200)),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('bank_account', models.CharField(blank=True, max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_branch', models.CharField(blank=True, max_length=100)),
                ('ifsc_code', models.CharField(blank=True, max_length=11)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_type', models.CharField(choices=[('Monthly', 'Monthly'), ('Contract', 'Contract'), ('Hourly', 'Hourly')], default='Monthly', max_length=20)),
                ('is_class_teacher', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('leaving_date', models.DateField(blank=True, null=True)),
                ('leaving_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_teacher_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher_info', to='courses.class')),
                ('subjects', models.ManyToManyField(related_name='teachers', to='courses.subject')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'ordering': ['employee_id'],
            },
        ),
    ]
